[package]
name = "rdxl"
version = "0.1.3"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Rusty Domain Extensible Language"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = { version="1.0", features=["span-locations"] }

[[bin]]
name = "example_simple"
path = "examples/simple.rs"

[[bin]]
name = "example_tags"
path = "examples/tags.rs"
