[package]
name = "rdxl"
version = "0.3.2"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT OR Apache-2.0"
description = "Rusty Domain Extensible Language"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/rdxl"
keywords = ["xml","html","templating","library"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = { version="1.0", features=["span-locations"] }

[dependencies.syn]
version = "1.0"
features = ["full"]

[[example]]
name = "cond"
file = "examples/cond.rs"

[[example]]
name = "context"
file = "examples/context.rs"

[[example]]
name = "formatter"
file = "examples/formatter.rs"

[[example]]
name = "loops"
file = "examples/loops.rs"

[[example]]
name = "misc"
file = "examples/misc.rs"

[[example]]
name = "simple"
file = "examples/simple.rs"

[[example]]
name = "tags"
file = "examples/tags.rs"

[[example]]
name = "vars"
file = "examples/vars.rs"
