[package]
name = "rdxl"
version = "0.1.17"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Rusty Domain Extensible Language"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/rdxl"
keywords = ["xml","html","templating","library"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = { version="1.0", features=["span-locations"] }

[dependencies.syn]
version = "1.0"
features = ["full"]

[[bin]]
name = "example_simple"
path = "examples/simple.rs"

[[bin]]
name = "example_tags"
path = "examples/tags.rs"

[[bin]]
name = "example_vars"
path = "examples/vars.rs"

[[bin]]
name = "example_loops"
path = "examples/loops.rs"

[[bin]]
name = "example_misc"
path = "examples/misc.rs"

[[bin]]
name = "example_cond"
path = "examples/cond.rs"

[[bin]]
name = "example_context"
path = "examples/context.rs"

[[bin]]
name = "example_formatter"
path = "examples/formatter.rs"
